import { prisma } from '../lib/prisma.js';
import { toNameSlug } from '../lib/slugUtils.js';

const PRODUCTS = [
    // ── Bread ───────────────────────────────────────────────────────────
    {
        name: 'Country Sourdough Loaf',
        description: 'Crusty naturally-leavened sourdough, baked daily with a 24-hour cold retard.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2023-03/Pain-De-Campagne_0961.jpg?itok=peSHWsFR',
        type: 'bread',
        price: 8,
        stock: 20,
    },
    {
        name: 'Seeded Rye Loaf',
        description: 'Dense dark-rye crumb loaded with caraway, sunflower, and flax seeds.',
        imageUrl: 'https://dontwasteyourtaste.com/wp-content/uploads/2021/01/Seeded-Rye-Sourdough-Bread-1020-px-.jpg',
        type: 'bread',
        price: 9,
        stock: 18,
    },
    {
        name: 'Honey Whole Wheat',
        description: 'Soft sandwich loaf made with 100% stone-milled whole wheat and local honey.',
        imageUrl: 'https://suebeehomemaker.com/wp-content/uploads/2023/11/honey-wheat-bread-recipecard.jpg',
        type: 'bread',
        price: 8,
        stock: 22,
    },
    {
        name: 'Olive & Rosemary Focaccia',
        description: 'Sheet-pan focaccia dimpled with Castelvetrano olives and fresh rosemary.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDFkQTUEB3_B25ibly0OMwtLo2stxuPprp1Q&s',
        type: 'bread',
        price: 10,
        stock: 15,
    },
    {
        name: 'Garlic Herb Baguette',
        description: 'Classic French baguette brushed with roasted garlic and herb butter.',
        imageUrl: 'https://weekdaypescatarian.com/wp-content/uploads/2022/12/IMG_8765-e1707222886192.jpg',
        type: 'bread',
        price: 6,
        stock: 25,
    },
    {
        name: 'Multigrain Sandwich Loaf',
        description: 'Seven-grain blend for a nutty, hearty everyday loaf with a tender crumb.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/blog-featured/multigrain-sandwich-loaf-18_0.jpg',
        type: 'bread',
        price: 9,
        stock: 20,
    },
    {
        name: 'Walnut Levain',
        description: 'Open-crumb levain studded with toasted walnuts; pairs well with aged cheese.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2022-12/Fig-Walnut-Sourdough-Bread-1855-01.jpg?itok=k97UaoJG',
        type: 'bread',
        price: 11,
        stock: 16,
    },
    {
        name: 'Cinnamon Raisin Swirl',
        description: 'Enriched dough rolled tight with brown-sugar cinnamon and plump California raisins.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2021-09/cinnamon-swirl-bread.jpg?itok=-OtL2DMT',
        type: 'bread',
        price: 9,
        stock: 18,
    },
    {
        name: 'Jalapeño Cheddar Loaf',
        description: 'Sourdough base with pockets of sharp cheddar and fresh jalapeño throughout.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2022-06/Artisan-Jalapeno-Bread_0496.jpg?itok=p_VTxwOC',
        type: 'bread',
        price: 11,
        stock: 14,
    },
    {
        name: 'Dark Pumpernickel',
        description: 'Slow-baked, extra-dark rye with molasses — deep earthy flavor, dense slice.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2025-05/Classic-Pumpernickel-Bread-7.jpg',
        type: 'bread',
        price: 10,
        stock: 15,
    },

    // ── Pastry ──────────────────────────────────────────────────────────
    {
        name: 'Butter Croissant',
        description: 'Flaky all-butter croissant with 27 laminated layers, baked to order each morning.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/800px-Croissant-Petr_Kratochvil.jpg',
        type: 'pastry',
        price: 4,
        stock: 30,
    },
    {
        name: 'Pain au Chocolat',
        description: 'Two bars of Valrhona dark chocolate sealed inside laminated croissant dough.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pain_au_chocolat_Luc_Viatour.jpg/800px-Pain_au_chocolat_Luc_Viatour.jpg',
        type: 'pastry',
        price: 5,
        stock: 28,
    },
    {
        name: 'Almond Croissant',
        description: 'Day-old croissant soaked in syrup, filled and topped with frangipane and sliced almonds.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Almond_Croissant_%2853378640779%29.jpg',
        type: 'pastry',
        price: 5,
        stock: 24,
    },
    {
        name: 'Ham & Gruyère Croissant',
        description: 'Savory croissant rolled with Black Forest ham and melted Gruyère.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Fillmore_Bakeshop_Ham_and_Cheese_Croissant_1_%2815246717038%29.jpg',
        type: 'pastry',
        price: 7,
        stock: 20,
    },
    {
        name: 'Cinnamon Morning Bun',
        description: 'Croissant dough coiled with orange-cinnamon sugar and finished in raw turbinado.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2025-03/Fruit-Filled-Morning-Buns-8.jpg?itok=l3kQXNDd',
        type: 'pastry',
        price: 5,
        stock: 25,
    },
    {
        name: 'Kouign-Amann',
        description: 'Breton caramelized pastry with a crackly sugar crust and buttery, chewy center.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Kouignamann.JPG',
        type: 'pastry',
        price: 6,
        stock: 20,
    },
    {
        name: 'Cheese Danish',
        description: 'Open-faced puff pastry topped with sweetened cream cheese and apricot glaze.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Cheese_danish_-_Massachusetts.jpg',
        type: 'pastry',
        price: 5,
        stock: 22,
    },
    {
        name: 'Apple Turnover',
        description: 'Puff-pastry pocket filled with spiced Granny Smith apple compote, dusted with powdered sugar.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Pastry-Turnover-Apple.jpg',
        type: 'pastry',
        price: 5,
        stock: 22,
    },
    {
        name: 'Strawberry Galette',
        description: 'Rustic free-form tart of buttery rough puff, fresh strawberries, and vanilla pastry cream.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Strawberry_galette.jpg',
        type: 'pastry',
        price: 6,
        stock: 18,
    },
    {
        name: 'Blueberry Hand Pie',
        description: 'Flaky all-butter crust packed with wild blueberry filling and a honey-butter wash.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lucie%27s_Blueberry_Hand_Pies_%2815121592525%29.jpg/800px-Lucie%27s_Blueberry_Hand_Pies_%2815121592525%29.jpg',
        type: 'pastry',
        price: 5,
        stock: 24,
    },

    // ── Cake ────────────────────────────────────────────────────────────
    {
        name: 'Chocolate Layer Cake',
        description: 'Three layers of Dutch-process chocolate sponge with whipped dark ganache.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/recipe_legacy/7135-3-large.jpg?itok=MwOCrCFw',
        type: 'cake',
        price: 28,
        stock: 8,
    },
    {
        name: 'Classic Vanilla Birthday Cake',
        description: 'Fluffy vanilla bean sponge layered with Swiss meringue buttercream and rainbow sprinkles.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2020-04/classic-birthday-cake-alt.jpg?itok=4EDTy1Ee',
        type: 'cake',
        price: 26,
        stock: 8,
    },
    {
        name: 'Lemon Olive Oil Cake',
        description: 'Fragrant, moist single-layer cake with Meyer lemon zest and a crème fraîche glaze.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2022-05/lemon-bliss-cake-8_1116.jpg?itok=mXWZBhNI',
        type: 'cake',
        price: 24,
        stock: 10,
    },
    {
        name: 'Carrot Cake',
        description: 'Spiced three-layer carrot cake with toasted walnuts and tangy cream cheese frosting.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2025-04/King-Arthurs-Carrot-Cake-2.jpg?itok=Lp8TLSOE',
        type: 'cake',
        price: 27,
        stock: 8,
    },
    {
        name: 'Red Velvet Cake',
        description: 'Deep crimson sponge with a hint of cocoa, layered with classic cream cheese frosting.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2019-11/red-velvet-cake.jpg?itok=ZrAwC52S',
        type: 'cake',
        price: 28,
        stock: 7,
    },
    {
        name: 'Strawberry Shortcake',
        description: 'Light génoise soaked in strawberry syrup, with fresh berries and whipped cream.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2021-05/genoise.jpg?itok=W9t978fq',
        type: 'cake',
        price: 25,
        stock: 9,
    },
    {
        name: 'Tiramisu Cake',
        description: 'Espresso-soaked ladyfinger layers under a cloud of mascarpone cream, dusted with cocoa.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2021-05/Tiramisu-908.jpg?itok=-FCG06F9',
        type: 'cake',
        price: 30,
        stock: 6,
    },
    {
        name: 'Blackberry Lavender Cake',
        description: 'Lavender-infused sponge with blackberry compote and honey mascarpone frosting.',
        imageUrl: 'https://sallysbakingaddiction.com/wp-content/uploads/2019/04/blackberry-lavender-cake.jpg',
        type: 'cake',
        price: 30,
        stock: 6,
    },
    {
        name: 'Salted Caramel Cheesecake',
        description: 'New York-style cheesecake on a graham cracker base, topped with house salted caramel.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2019-10/caramel-pecan-cheesecake.jpg?itok=EfQS259g',
        type: 'cake',
        price: 32,
        stock: 6,
    },
    {
        name: 'Pistachio Rosewater Cake',
        description: 'Ground pistachio sponge scented with rosewater, finished with cardamom whipped cream.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/2024-09/PistachioCake_Product_HOR_167.jpg?itok=a3e_4Oyn',
        type: 'cake',
        price: 32,
        stock: 5,
    },

    // ── Cookie ──────────────────────────────────────────────────────────
    {
        name: 'Chocolate Chip Cookie',
        description: 'Warm, chewy, with dark chocolate chunks and flaky sea salt on top.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Chocolate_chip_cookie.jpg',
        type: 'cookie',
        price: 3,
        stock: 50,
    },
    {
        name: 'Brown Butter Snickerdoodle',
        description: 'Browned-butter base rolled in cinnamon sugar with a signature cream-of-tartar tang.',
        imageUrl: 'https://sallysbakingaddiction.com/wp-content/uploads/2013/05/snickerdoodles.jpg',
        type: 'cookie',
        price: 3,
        stock: 50,
    },
    {
        name: 'Espresso Shortbread',
        description: 'Crumbly butter shortbread charged with finely ground espresso and dipped in dark chocolate.',
        imageUrl: 'https://www.theflavorbender.com/wp-content/uploads/2015/03/Espresso-Shortbread-3991-700x1049.jpg',
        type: 'cookie',
        price: 4,
        stock: 45,
    },
    {
        name: 'Salted Oatmeal Raisin',
        description: 'Thick, chewy oatmeal cookie with plump raisins and a generous pinch of fleur de sel.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/71/Oatmeal_raisin_cookie.jpg',
        type: 'cookie',
        price: 3,
        stock: 50,
    },
    {
        name: 'Tahini Sesame Cookie',
        description: 'Nutty tahini dough rolled in toasted sesame seeds — crisp edge, fudgy center.',
        imageUrl: 'https://feelgoodfoodie.net/wp-content/uploads/2020/04/Honey-Tahini-Cookies-09.jpg',
        type: 'cookie',
        price: 4,
        stock: 40,
    },
    {
        name: 'Double Chocolate Brownie Cookie',
        description: 'Fudgy brownie batter baked into cookie form — crinkle top, gooey center.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Chocolate_Crinkles.jpg',
        type: 'cookie',
        price: 4,
        stock: 45,
    },
    {
        name: 'Lemon Glazed Sugar Cookie',
        description: 'Soft cut-out sugar cookie with a puckery lemon royal-icing glaze.',
        imageUrl: 'https://sallysbakingaddiction.com/wp-content/uploads/2024/12/iced-lemon-shortbread-cookies.jpg',
        type: 'cookie',
        price: 3,
        stock: 55,
    },
    {
        name: 'Peanut Butter Blossom',
        description: 'Classic peanut butter cookie pressed with a Valrhona dark chocolate disc while hot.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/2022-01-01_00_57_47_A_Hershey_Kiss_cookies_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg',
        type: 'cookie',
        price: 3,
        stock: 50,
    },
    {
        name: 'Matcha White Chocolate Cookie',
        description: 'Ceremonial-grade matcha dough studded with chunks of creamy white chocolate.',
        imageUrl: 'https://www.justonecookbook.com/wp-content/uploads/2021/01/Green-Tea-Cookies-3651-I.jpg',
        type: 'cookie',
        price: 4,
        stock: 40,
    },
    {
        name: 'Cardamom Almond Thumbprint',
        description: 'Buttery almond dough spiced with cardamom, thumbed and filled with apricot jam.',
        imageUrl: 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image_sm/public/recipe_legacy/6117-3-large.jpg?itok=kTqEbF4H',
        type: 'cookie',
        price: 4,
        stock: 40,
    },

    // ── Drink ───────────────────────────────────────────────────────────
    {
        name: 'House Latte',
        description: 'Double shot of house-blend espresso with steamed whole milk and latte art.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Latte_art_5.jpg',
        type: 'drink',
        price: 5,
        stock: 40,
    },
    {
        name: 'Cold Brew',
        description: '18-hour coarse-ground cold brew, served over ice — smooth and low-acid.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Iced_cold_brew_coffee.jpg',
        type: 'drink',
        price: 5,
        stock: 35,
    },
    {
        name: 'Oat Milk Cappuccino',
        description: 'Equal parts ristretto, steamed oat milk, and thick oat-milk foam.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Cappuccino_Chiang_Mai.JPG',
        type: 'drink',
        price: 6,
        stock: 35,
    },
    {
        name: 'Matcha Latte',
        description: 'Ceremonial-grade matcha whisked with a splash of hot water, topped with steamed oat milk.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Matcha_Latte_KF.JPG',
        type: 'drink',
        price: 6,
        stock: 30,
    },
    {
        name: 'Chai Spice Latte',
        description: 'House-made masala chai concentrate with steamed milk and a dusting of cinnamon.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/Masala_Chai.JPG',
        type: 'drink',
        price: 6,
        stock: 30,
    },
    {
        name: 'Honey Lavender Lemonade',
        description: 'Fresh-squeezed lemonade sweetened with lavender-infused honey syrup, served over ice.',
        imageUrl: 'https://images.unsplash.com/photo-1750665645102-dfefd863316c?fm=jpg&q=60&w=3000&auto=format&fit=crop',
        type: 'drink',
        price: 5,
        stock: 40,
    },
    {
        name: 'Strawberry Rose Lemonade',
        description: 'Cold-pressed lemonade blended with fresh strawberry purée and a hint of rosewater.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Costa_Stawberry_Lemonade.jpg',
        type: 'drink',
        price: 5,
        stock: 40,
    },
    {
        name: 'Sparkling Yuzu Soda',
        description: 'House yuzu cordial topped with sparkling water — bright, tart, and floral.',
        imageUrl: 'https://images.unsplash.com/photo-1621330716555-5cad596c4562?fm=jpg&q=60&w=3000&auto=format&fit=crop',
        type: 'drink',
        price: 5,
        stock: 35,
    },
    {
        name: 'Turmeric Golden Milk Latte',
        description: 'Steamed oat milk with turmeric, ginger, black pepper, and a touch of maple syrup.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Golden_turmeric_latte_-_Hello_My_Moon_2024-04-07.jpg',
        type: 'drink',
        price: 6,
        stock: 30,
    },
    {
        name: 'Iced Horchata',
        description: 'House rice-and-almond horchata spiced with cinnamon, served over crushed ice.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Horchata_%2850943998568%29.jpg',
        type: 'drink',
        price: 5,
        stock: 35,
    },
];

async function main() {
    for (const p of PRODUCTS) {
        const existing = await prisma.product.findFirst({ where: { name: p.name } });
        if (existing) {
            const { stock: _seedStock, ...rest } = p;
            await prisma.product.update({ where: { id: existing.id }, data: rest });
            console.log(`updated: ${p.name}`);
        } else {
            await prisma.product.create({ data: { ...p, slug: toNameSlug(p.name) } });
            console.log(`created: ${p.name}`);
        }
    }
}

main()
    .then(() => prisma.$disconnect())
    .catch(async (err) => {
        console.error(err);
        await prisma.$disconnect();
        process.exit(1);
    });
